button_close = 'Close'
button_confirm = 'Confirm'
button_no = 'No'
button_save = 'Save'
button_yes = 'Yes'

input_adjust_score = 'Adjust score'
input_custom = 'Enter custom cash value'
input_name = 'Edit player name'

label_category = 'Category'
label_clue = 'Clue'
label_name = 'Name'
label_name_exists = 'A puzzle with the name "{}" already exists.\nOverwrite?'

mgr_btn_bankrupt = 'Bankrupt'
mgr_btn_buy_vowel = 'Buy a\nvowel'
mgr_btn_lose_turn = 'Lose a\nturn'
mgr_btn_reveal = 'Reveal Puzzle'
mgr_btn_solve = 'Solve'
mgr_btn_tossup = 'Toss-up'
mgr_label_puzzle = 'Current Puzzle:\n'
mgr_label_clue = 'Clue:\n'
mgr_select_value = 'Select cash value'

title_choose_letter = 'Choose a letter'
title_name_exists = 'Name exists'
title_save_puzzle = 'Save puzzle'
title_select_puzzle = 'Select puzzle'
